theme: jekyll-theme-tactile
title: The Kastelo Hardware Wallet Project
description: This portal serves information relating to the official Monero Hardwallet, created by a team of Monero enthusiasts on a project code named Kastelo.
